<?php

use Carbon\Carbon;

/**
 * Class StockHistoryData
 */
class StockHistoryData
{
    /**
     * @return array
     */
    public static function getDataList()
    {
        $now = Carbon::now();

        return [
            [
                'location_id' => 1,
                'lot_id' => 7,
                'stock_history_type_id' => 2,
                'quantity' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 2,
                'lot_id' => 7,
                'stock_history_type_id' => 2,
                'quantity' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 1,
                'lot_id' => 8,
                'stock_history_type_id' => 2,
                'quantity' => 13,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 2,
                'lot_id' => 8,
                'stock_history_type_id' => 2,
                'quantity' => 122,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 3,
                'lot_id' => 8,
                'stock_history_type_id' => 2,
                'quantity' => 67,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 6,
                'lot_id' => 8,
                'stock_history_type_id' => 2,
                'quantity' => 17,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 1,
                'lot_id' => 9,
                'stock_history_type_id' => 2,
                'quantity' => 8,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 2,
                'lot_id' => 9,
                'stock_history_type_id' => 2,
                'quantity' => 458,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 3,
                'lot_id' => 9,
                'stock_history_type_id' => 2,
                'quantity' => 40,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 6,
                'lot_id' => 9,
                'stock_history_type_id' => 2,
                'quantity' => 429,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 2,
                'lot_id' => 10,
                'stock_history_type_id' => 2,
                'quantity' => 682,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 1,
                'lot_id' => 11,
                'stock_history_type_id' => 2,
                'quantity' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 2,
                'lot_id' => 11,
                'stock_history_type_id' => 2,
                'quantity' => 175,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 2,
                'lot_id' => 13,
                'stock_history_type_id' => 2,
                'quantity' => 27,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 3,
                'lot_id' => 13,
                'stock_history_type_id' => 2,
                'quantity' => 40,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 1,
                'lot_id' => 15,
                'stock_history_type_id' => 2,
                'quantity' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 2,
                'lot_id' => 15,
                'stock_history_type_id' => 2,
                'quantity' => 64,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 3,
                'lot_id' => 17,
                'stock_history_type_id' => 2,
                'quantity' => 72,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 1,
                'lot_id' => 20,
                'stock_history_type_id' => 2,
                'quantity' => 20,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 2,
                'lot_id' => 20,
                'stock_history_type_id' => 2,
                'quantity' => 818,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 4,
                'lot_id' => 20,
                'stock_history_type_id' => 2,
                'quantity' => 250,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 6,
                'lot_id' => 20,
                'stock_history_type_id' => 2,
                'quantity' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 1,
                'lot_id' => 21,
                'stock_history_type_id' => 2,
                'quantity' => 6,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 2,
                'lot_id' => 21,
                'stock_history_type_id' => 2,
                'quantity' => 17,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 4,
                'lot_id' => 21,
                'stock_history_type_id' => 2,
                'quantity' => 3900,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 1,
                'lot_id' => 22,
                'stock_history_type_id' => 2,
                'quantity' => 80,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 2,
                'lot_id' => 22,
                'stock_history_type_id' => 2,
                'quantity' => 165,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 1,
                'lot_id' => 23,
                'stock_history_type_id' => 2,
                'quantity' => 877,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 2,
                'lot_id' => 23,
                'stock_history_type_id' => 2,
                'quantity' => 516,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 4,
                'lot_id' => 23,
                'stock_history_type_id' => 2,
                'quantity' => 3750,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 5,
                'lot_id' => 23,
                'stock_history_type_id' => 2,
                'quantity' => 1009,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 1,
                'lot_id' => 24,
                'stock_history_type_id' => 2,
                'quantity' => 6,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 2,
                'lot_id' => 24,
                'stock_history_type_id' => 2,
                'quantity' => 370,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 4,
                'lot_id' => 24,
                'stock_history_type_id' => 2,
                'quantity' => 3750,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 6,
                'lot_id' => 24,
                'stock_history_type_id' => 2,
                'quantity' => 900,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 1,
                'lot_id' => 25,
                'stock_history_type_id' => 2,
                'quantity' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 2,
                'lot_id' => 25,
                'stock_history_type_id' => 2,
                'quantity' => 70,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 4,
                'lot_id' => 25,
                'stock_history_type_id' => 2,
                'quantity' => 3900,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 1,
                'lot_id' => 26,
                'stock_history_type_id' => 2,
                'quantity' => 112,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 2,
                'lot_id' => 26,
                'stock_history_type_id' => 2,
                'quantity' => 13,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 4,
                'lot_id' => 26,
                'stock_history_type_id' => 2,
                'quantity' => 2600,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 1,
                'lot_id' => 27,
                'stock_history_type_id' => 2,
                'quantity' => 171,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 2,
                'lot_id' => 27,
                'stock_history_type_id' => 2,
                'quantity' => 48,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 4,
                'lot_id' => 27,
                'stock_history_type_id' => 2,
                'quantity' => 2880,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 5,
                'lot_id' => 27,
                'stock_history_type_id' => 2,
                'quantity' => 440,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 1,
                'lot_id' => 28,
                'stock_history_type_id' => 2,
                'quantity' => 8,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 2,
                'lot_id' => 28,
                'stock_history_type_id' => 2,
                'quantity' => 473,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 5,
                'lot_id' => 28,
                'stock_history_type_id' => 2,
                'quantity' => 3600,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 6,
                'lot_id' => 28,
                'stock_history_type_id' => 2,
                'quantity' => 280,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 1,
                'lot_id' => 29,
                'stock_history_type_id' => 2,
                'quantity' => 1128,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 2,
                'lot_id' => 29,
                'stock_history_type_id' => 2,
                'quantity' => 19,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 4,
                'lot_id' => 29,
                'stock_history_type_id' => 2,
                'quantity' => 2000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 5,
                'lot_id' => 29,
                'stock_history_type_id' => 2,
                'quantity' => 820,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 1,
                'lot_id' => 30,
                'stock_history_type_id' => 2,
                'quantity' => 19,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 2,
                'lot_id' => 30,
                'stock_history_type_id' => 2,
                'quantity' => 40,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 4,
                'lot_id' => 30,
                'stock_history_type_id' => 2,
                'quantity' => 700,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 5,
                'lot_id' => 30,
                'stock_history_type_id' => 2,
                'quantity' => 820,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 1,
                'lot_id' => 31,
                'stock_history_type_id' => 2,
                'quantity' => 29,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 2,
                'lot_id' => 31,
                'stock_history_type_id' => 2,
                'quantity' => 90,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'location_id' => 2,
                'lot_id' => 32,
                'stock_history_type_id' => 2,
                'quantity' => 958,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];
    }
}
